import { z } from "zod"

export const CATEGORIES = [
    "AI",
    "Frontend",
    "Backend",
    "Mobile",
    "Cloud",
    "DevOps",
    "Database",
    "Security",
    "Performance",
    "Architecture",
    "System Design",
    "Distributed Systems",
    "Platform Engineering",
    "Developer Tools",
    "Observability",
    "Networking",
    "Data Engineering",
    "Testing",
    "Open Source",
    "Engineering Culture",
    "Case Study",
    "Best Practices",
    "Tutorial",
    "Career",
    "Product Engineering",
] as const;


export const TAGS = [
    "javascript",
    "typescript",
    "python",
    "golang",
    "rust",
    "java",
    "csharp",
    "php",
    "ruby",
    "swift",
    "react",
    "nextjs",
    "vue",
    "angular",
    "svelte",
    "html",
    "css",
    "tailwindcss",
    "vite",
    "web-components",
    "nodejs",
    "express",
    "nestjs",
    "graphql",
    "rest-api",
    "grpc",
    "websockets",
    "authentication",
    "authorization",
    "api-design",
    "postgresql",
    "mysql",
    "mongodb",
    "redis",
    "sqlite",
    "elasticsearch",
    "orm",
    "database-design",
    "query-optimization",
    "caching",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "terraform",
    "github-actions",
    "ci-cd",
    "serverless",
    "linux",
    "ai",
    "machine-learning",
    "deep-learning",
    "generative-ai",
    "llms",
    "rag",
    "ai-agents",
    "prompt-engineering",
    "embeddings",
    "vector-database",
    "system-design",
    "microservices",
    "distributed-systems",
    "event-driven",
    "message-queues",
    "architecture",
    "scalability",
    "high-availability",
    "fault-tolerance",
    "design-patterns",
    "testing",
    "performance",
    "security",
    "observability",
    "monitoring",
    "logging",
    "debugging",
    "refactoring",
    "clean-code",
    "code-quality",
    "case-study",
    "best-practices",
    "tutorial",
    "engineering-culture",
    "developer-experience",
    "developer-tools",
    "open-source",
    "product-engineering",
    "career",
    "interview",
] as const;


export const schema = {
    type: "object",
    properties: {
        author: { type: "string" },
        summary: { type: "string" },
        category: {
            type: "array",
            maxItems: 3,
            items: { type: "string" },
        },
        tags: {
            type: "array",
            maxItems: 5,
            items: { type: "string"},
        },
        keyTakeaways: { type: "string" },
        whyRead: { type: "string" },
        difficulty: { type: "string", enum: ["junior", "mid", "senior"] },
    },
    required: [
        "author",
        "summary",
        "category",
        "tags",
        "keyTakeaways",
        "whyRead",
        "difficulty",
    ],
};

export const metadataSchema = z.fromJSONSchema(schema as Parameters<typeof z.fromJSONSchema>[0]);
