export const articleCategories = [
    { value: "ai", label: "Artificial Intelligence" },
    { value: "frontend", label: "Frontend" },
    { value: "backend", label: "Backend" },
    { value: "mobile", label: "Mobile Development" },
    { value: "cloud", label: "Cloud Computing" },
    { value: "devops", label: "DevOps" },
    { value: "database", label: "Databases" },
    { value: "security", label: "Security" },
    { value: "performance", label: "Performance" },
    { value: "architecture", label: "Software Architecture" },
    { value: "system-design", label: "System Design" },
    { value: "distributed-systems", label: "Distributed Systems" },
    { value: "platform-engineering", label: "Platform Engineering" },
    { value: "developer-tools", label: "Developer Tools" },
    { value: "observability", label: "Observability" },
    { value: "networking", label: "Networking" },
    { value: "data-engineering", label: "Data Engineering" },
    { value: "testing", label: "Testing & QA" },
    { value: "open-source", label: "Open Source" },
    { value: "engineering-culture", label: "Engineering Culture" },
    { value: "case-study", label: "Case Studies" },
    { value: "best-practices", label: "Best Practices" },
    { value: "tutorial", label: "Tutorials" },
    { value: "career", label: "Career & Learning" },
    { value: "product-engineering", label: "Product Engineering" },
] as const;