export const userTags = [
    // Languages
    { value: "javascript", label: "JavaScript" },
    { value: "typescript", label: "TypeScript" },
    { value: "python", label: "Python" },
    { value: "golang", label: "Go" },
    { value: "rust", label: "Rust" },
    { value: "java", label: "Java" },
    { value: "csharp", label: "C#" },
    { value: "php", label: "PHP" },
    { value: "ruby", label: "Ruby" },
    { value: "swift", label: "Swift" },

    // Frontend
    { value: "react", label: "React" },
    { value: "nextjs", label: "Next.js" },
    { value: "vue", label: "Vue.js" },
    { value: "angular", label: "Angular" },
    { value: "svelte", label: "Svelte" },
    { value: "html", label: "HTML" },
    { value: "css", label: "CSS" },
    { value: "tailwindcss", label: "Tailwind CSS" },
    { value: "vite", label: "Vite" },
    { value: "web-components", label: "Web Components" },

    // Backend
    { value: "nodejs", label: "Node.js" },
    { value: "express", label: "Express.js" },
    { value: "nestjs", label: "NestJS" },
    { value: "graphql", label: "GraphQL" },
    { value: "rest-api", label: "REST API" },
    { value: "grpc", label: "gRPC" },
    { value: "websockets", label: "WebSockets" },
    { value: "authentication", label: "Authentication" },
    { value: "authorization", label: "Authorization" },
    { value: "api-design", label: "API Design" },

    // Database
    { value: "postgresql", label: "PostgreSQL" },
    { value: "mysql", label: "MySQL" },
    { value: "mongodb", label: "MongoDB" },
    { value: "redis", label: "Redis" },
    { value: "sqlite", label: "SQLite" },
    { value: "elasticsearch", label: "Elasticsearch" },
    { value: "orm", label: "ORM" },
    { value: "database-design", label: "Database Design" },
    { value: "query-optimization", label: "Query Optimization" },
    { value: "caching", label: "Caching" },

    // Cloud & DevOps
    { value: "docker", label: "Docker" },
    { value: "kubernetes", label: "Kubernetes" },
    { value: "aws", label: "AWS" },
    { value: "azure", label: "Azure" },
    { value: "gcp", label: "Google Cloud" },
    { value: "terraform", label: "Terraform" },
    { value: "github-actions", label: "GitHub Actions" },
    { value: "ci-cd", label: "CI/CD" },
    { value: "serverless", label: "Serverless" },
    { value: "linux", label: "Linux" },

    // AI
    { value: "ai", label: "Artificial Intelligence" },
    { value: "machine-learning", label: "Machine Learning" },
    { value: "deep-learning", label: "Deep Learning" },
    { value: "generative-ai", label: "Generative AI" },
    { value: "llms", label: "LLMs" },
    { value: "rag", label: "RAG" },
    { value: "ai-agents", label: "AI Agents" },
    { value: "prompt-engineering", label: "Prompt Engineering" },
    { value: "embeddings", label: "Embeddings" },
    { value: "vector-database", label: "Vector Database" },

    // Architecture
    { value: "system-design", label: "System Design" },
    { value: "microservices", label: "Microservices" },
    { value: "distributed-systems", label: "Distributed Systems" },
    { value: "event-driven", label: "Event Driven" },
    { value: "message-queues", label: "Message Queues" },
    { value: "architecture", label: "Software Architecture" },
    { value: "scalability", label: "Scalability" },
    { value: "high-availability", label: "High Availability" },
    { value: "fault-tolerance", label: "Fault Tolerance" },
    { value: "design-patterns", label: "Design Patterns" },

    // Quality
    { value: "testing", label: "Testing" },
    { value: "performance", label: "Performance" },
    { value: "security", label: "Security" },
    { value: "observability", label: "Observability" },
    { value: "monitoring", label: "Monitoring" },
    { value: "logging", label: "Logging" },
    { value: "debugging", label: "Debugging" },
    { value: "refactoring", label: "Refactoring" },
    { value: "clean-code", label: "Clean Code" },
    { value: "code-quality", label: "Code Quality" },

    // Engineering
    { value: "case-study", label: "Case Study" },
    { value: "best-practices", label: "Best Practices" },
    { value: "tutorial", label: "Tutorial" },
    { value: "engineering-culture", label: "Engineering Culture" },
    { value: "developer-experience", label: "Developer Experience" },
    { value: "developer-tools", label: "Developer Tools" },
    { value: "open-source", label: "Open Source" },
    { value: "product-engineering", label: "Product Engineering" },
    { value: "career", label: "Career" },
    { value: "interview", label: "Interview" },
] as const;

export const userInterests = userTags;


// tag mapping with alias
type TagAliasMap = Record<string, string[]>;

export const TagsAlias: TagAliasMap = {
    "javascript": ["js", "es6", "ecmascript", "vanilla js", "vanillajs", "js tricks", "modern javascript", "async javascript"],
    "typescript": ["ts", "typed javascript", "tsconfig", "type safety", "generics in typescript", "ts types"],
    "python": ["py", "python3", "cpython", "pythonic", "python scripting", "python3.x"],
    "golang": ["go", "go lang", "golang tutorial", "goroutines", "go modules"],
    "rust": ["rustlang", "rust programming", "cargo", "ownership and borrowing", "rust memory safety"],
    "java": ["java se", "jvm", "java programming", "openjdk", "java spring"],
    "csharp": ["c#", "c-sharp", "dotnet", ".net", "csharp programming"],
    "php": ["php7", "php8", "laravel php", "php scripting"],
    "ruby": ["ruby lang", "ruby on rails", "rails", "rb"],
    "swift": ["swiftui", "swift programming", "ios swift", "apple swift"],
    "react": ["reactjs", "react.js", "react hooks", "react components", "jsx", "react state management"],
    "nextjs": ["next.js", "next js", "app router", "next.js ssr", "vercel next"],
    "vue": ["vuejs", "vue.js", "vue composition api", "vue3"],
    "angular": ["angularjs", "angular2+", "angular framework", "ng"],
    "svelte": ["sveltejs", "svelte.js", "sveltekit"],
    "html": ["html5", "markup", "semantic html", "html tags"],
    "css": ["css3", "stylesheets", "css styling", "cascading style sheets"],
    "tailwindcss": ["tailwind", "tailwind css", "utility-first css"],
    "vite": ["vitejs", "vite.js", "vite bundler", "vite build tool"],
    "web-components": ["custom elements", "shadow dom", "web component", "native components"],
    "nodejs": ["node.js", "node js", "node", "node backend"],
    "express": ["expressjs", "express.js", "express middleware", "express server"],
    "nestjs": ["nest.js", "nest js", "nest framework"],
    "graphql": ["gql", "graphql api", "graphql schema", "apollo graphql"],
    "rest-api": ["restful api", "rest apis", "restful services", "rest endpoints", "api rest"],
    "grpc": ["grpc api", "protocol buffers", "protobuf", "remote procedure call"],
    "websockets": ["websocket", "ws protocol", "socket.io", "real-time communication", "bidirectional communication"],
    "authentication": ["auth", "login system", "user auth", "oauth", "jwt auth", "sso"],
    "authorization": ["authz", "access control", "rbac", "permissions", "role-based access"],
    "api-design": ["api architecture", "designing apis", "api best practices", "api versioning"],
    "postgresql": ["postgres", "psql", "pg", "postgresql database"],
    "mysql": ["my sql", "mariadb", "mysql database"],
    "mongodb": ["mongo", "mongo db", "nosql mongodb"],
    "redis": ["redis cache", "redis db", "in-memory store"],
    "sqlite": ["sqlite3", "sqlite database", "embedded database"],
    "elasticsearch": ["elastic search", "es", "elk stack", "full-text search"],
    "orm": ["object relational mapping", "prisma", "sequelize", "typeorm", "drizzle orm"],
    "database-design": ["db design", "schema design", "data modeling", "database schema"],
    "query-optimization": ["sql optimization", "query performance", "index optimization", "slow query tuning"],
    "caching": ["cache strategy", "cache layer", "memoization", "cdn caching"],
    "docker": ["dockerfile", "docker container", "containerization", "docker compose"],
    "kubernetes": ["k8s", "kube", "kubectl", "container orchestration"],
    "aws": ["amazon web services", "ec2", "s3", "aws cloud", "lambda aws"],
    "azure": ["microsoft azure", "azure cloud", "azure functions"],
    "gcp": ["google cloud platform", "google cloud", "gcp cloud"],
    "terraform": ["iac", "infrastructure as code", "terraform hcl", "tf modules"],
    "github-actions": ["gh actions", "github workflows", "github ci"],
    "ci-cd": ["continuous integration", "continuous deployment", "continuous delivery", "ci/cd pipeline", "build pipeline"],
    "serverless": ["faas", "function as a service", "serverless functions", "lambda functions"],
    "linux": ["gnu/linux", "linux cli", "bash", "linux system administration"],
    "ai": ["artificial intelligence", "ai systems", "ai technology"],
    "machine-learning": ["ml", "machine learning models", "supervised learning", "unsupervised learning"],
    "deep-learning": ["dl", "neural networks", "deep neural nets", "cnn", "rnn"],
    "generative-ai": ["genai", "gen ai", "generative models", "generative art ai"],
    "llms": ["large language models", "llm", "language models", "gpt models"],
    "rag": ["retrieval augmented generation", "retrieval-augmented generation", "rag pipeline"],
    "ai-agents": ["autonomous agents", "agentic ai", "llm agents", "agent workflows"],
    "prompt-engineering": ["prompt design", "prompting techniques", "prompt tuning"],
    "embeddings": ["vector embeddings", "text embeddings", "embedding models"],
    "vector-database": ["vector db", "vectordb", "qdrant", "pinecone", "vector store", "vector search"],
    "system-design": ["systems design", "system architecture", "designing systems"],
    "microservices": ["microservice architecture", "micro services", "service-oriented architecture"],
    "distributed-systems": ["distributed computing", "distributed architecture", "distributed systems design"],
    "event-driven": ["event-driven architecture", "eda", "event sourcing", "pub-sub"],
    "message-queues": ["message queue", "mq", "rabbitmq", "kafka", "queueing system"],
    "architecture": ["software architecture", "system architecture", "architectural patterns"],
    "scalability": ["scaling", "scalable systems", "horizontal scaling", "vertical scaling"],
    "high-availability": ["ha", "high-availability systems", "uptime", "failover"],
    "fault-tolerance": ["fault tolerant systems", "resilience", "resiliency", "graceful degradation"],
    "design-patterns": ["software design patterns", "gof patterns", "architectural design patterns"],
    "testing": ["unit testing", "integration testing", "test automation", "qa testing"],
    "performance": ["performance optimization", "performance tuning", "speed optimization", "perf"],
    "security": ["appsec", "cybersecurity", "application security", "infosec"],
    "observability": ["observability stack", "telemetry", "opentelemetry", "tracing"],
    "monitoring": ["app monitoring", "system monitoring", "metrics", "alerting"],
    "logging": ["log management", "structured logging", "log aggregation"],
    "debugging": ["debug", "troubleshooting", "bug fixing", "root cause analysis"],
    "refactoring": ["code refactoring", "codebase cleanup", "refactor"],
    "clean-code": ["clean coding", "readable code", "maintainable code"],
    "code-quality": ["code standards", "code review", "linting", "static analysis"],
    "case-study": ["case studies", "real-world example", "postmortem", "post-mortem"],
    "best-practices": ["industry best practices", "recommended practices", "guidelines"],
    "tutorial": ["how-to guide", "step-by-step guide", "walkthrough", "getting started guide"],
    "engineering-culture": ["eng culture", "team culture", "engineering org", "engineering management"],
    "developer-experience": ["dx", "dev experience", "developer productivity"],
    "developer-tools": ["dev tools", "devtools", "tooling", "cli tools"],
    "open-source": ["oss", "open source software", "foss"],
    "product-engineering": ["product eng", "product-minded engineering", "product development"],
    "career": ["career growth", "career advice", "career development", "job search"],
    "interview": ["interview prep", "coding interview", "technical interview", "interview questions"]
}