import { PageHeader } from "@/components/static/PageHeader";
import { ContentSection } from "@/components/static/ContentSection";
import { LegalSection, LegalCard } from "@/components/static/LegalSection";
import { MarkdownContent } from "@/components/static/MarkdownContent";
import { constructMetadata } from "@/lib/utils";

export const metadata = constructMetadata({
  title: "Terms of Service - BlogDrop",
  description: "Terms of Service for BlogDrop",
});

export default function TermsPage() {
  return (
    <>
      <PageHeader 
        title="Terms of Service" 
        updatedAt="July 2026"
      />
      
      <ContentSection>
        <MarkdownContent className="mb-8">
          <p>By using BlogDrop, you agree to the following terms.</p>
        </MarkdownContent>

        <LegalSection title="1. What BlogDrop is">
          <LegalCard>
            <MarkdownContent>
              <p>BlogDrop is a content aggregation service. We index publicly available RSS feeds from third-party engineering blogs, generate metadata (tags, categories, short summaries) using AI, and link users to the original source articles. <strong>We do not host, own, or claim rights to the full text of any aggregated article.</strong> All original content belongs to its respective publisher.</p>
            </MarkdownContent>
          </LegalCard>
        </LegalSection>

        <LegalSection title="2. Acceptable use">
          <LegalCard>
            <MarkdownContent>
              <p>You agree not to:</p>
              <ul>
                <li>Scrape, reverse-engineer, or bulk-extract BlogDrop&apos;s data or infrastructure</li>
                <li>Use BlogDrop to distribute malware, spam, or harmful content</li>
                <li>Attempt to bypass rate limits, authentication, or security controls</li>
                <li>Misrepresent your identity or impersonate another person or organization</li>
              </ul>
            </MarkdownContent>
          </LegalCard>
        </LegalSection>

        <LegalSection title="3. Accounts">
          <LegalCard>
            <MarkdownContent>
              <p>If BlogDrop offers accounts, you&apos;re responsible for maintaining the confidentiality of your login credentials and for all activity under your account. Notify us immediately of any unauthorized use.</p>
            </MarkdownContent>
          </LegalCard>
        </LegalSection>

        <LegalSection title="4. Content and intellectual property">
          <LegalCard>
            <MarkdownContent>
              <ul>
                <li>Article titles, summaries, and metadata generated by BlogDrop are provided for indexing/discovery purposes under fair use principles.</li>
                <li>Full article content remains the intellectual property of its original publisher. BlogDrop does not claim ownership.</li>
                <li>If you are a content owner and want your blog removed from BlogDrop, contact us and we will honor the request within 5 business days.</li>
                <li>The BlogDrop name, logo, and site design are the property of BlogDrop and may not be used without permission.</li>
              </ul>
            </MarkdownContent>
          </LegalCard>
        </LegalSection>

        <LegalSection title="5. No warranty">
          <LegalCard>
            <MarkdownContent>
              <p>BlogDrop is provided &quot;as is.&quot; We do not guarantee uptime, accuracy of AI-generated tags/summaries, or that linked third-party content will remain available. AI-generated summaries may occasionally be inaccurate — always refer to the original source for authoritative information.</p>
            </MarkdownContent>
          </LegalCard>
        </LegalSection>

        <LegalSection title="6. Limitation of liability">
          <LegalCard>
            <MarkdownContent>
              <p>To the maximum extent permitted by law, BlogDrop and its operator are not liable for any indirect, incidental, or consequential damages arising from your use of the service, including reliance on AI-generated summaries or third-party content accessed through BlogDrop.</p>
            </MarkdownContent>
          </LegalCard>
        </LegalSection>

        <LegalSection title="7. Termination">
          <LegalCard>
            <MarkdownContent>
              <p>We reserve the right to suspend or terminate accounts that violate these terms, at our discretion.</p>
            </MarkdownContent>
          </LegalCard>
        </LegalSection>

        <LegalSection title="8. Changes to these terms">
          <LegalCard>
            <MarkdownContent>
              <p>We may update these terms from time to time. Continued use of BlogDrop after changes constitutes acceptance of the new terms.</p>
            </MarkdownContent>
          </LegalCard>
        </LegalSection>

        <LegalSection title="9. Governing law">
          <LegalCard>
            <MarkdownContent>
              <p>These terms are governed by the laws of India, without regard to conflict-of-law principles.</p>
            </MarkdownContent>
          </LegalCard>
        </LegalSection>

        <LegalSection title="10. Contact">
          <LegalCard>
            <MarkdownContent>
              <p>Questions about these terms? Email legal@blogdrop.dev.</p>
            </MarkdownContent>
          </LegalCard>
        </LegalSection>

      </ContentSection>
    </>
  );
}
